### ISSUE TITLE
protect main branch

### ISSUE THREAD

**Issue by michlleon** [shanky-baby/u-and-co#22]
no unauthorized pushes

https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/managing-a-branch-protection-rule

I dont have access to main branch settings @moofShaw @shanky-baby one of you will have to do it, just look at the link should be pretty straight forward

**Comment by shanky-baby** [comment]
push and pull requests now require authorisation
